### ISSUE TITLE
Could you please upload the datasets you used in your paper?

### ISSUE THREAD

**Issue by WenjianDing** [luoyan407/n-reference#1]

**Comment by WenjianDing** [comment]
Or maybe you can upload the download link.

**Comment by luoyan407** [comment]
> Or maybe you can upload the download link.

Thanks for reaching out to me. I have updated the README.md to address your question. I both pointed to the download pages and made the preprocessed blurred fixation maps available.

**Comment by WenjianDing** [comment]
Received! Thanks.
